### ISSUE TITLE
HELP!! [BOJ] [BFS] [14502] [연구소] 

### ISSUE THREAD

**Issue by inseonyun** [hs-study-group/algorithm#165]
Source URL :  https://www.acmicpc.net/problem/14502

본인 문제 접근 방법 : 
1. 바이러스를 큐에 넣고, 해당 큐 좌표를 이용해서 바이러스 전이를 시킴 
2. map을 복사해가며, 벽을 세워 전이를 막아 안전 구역(0의 개수)를 최대화 해야하는 문제 같음

애로 사항 : 해당 문제 풀이 과정 및 문제 요구사항 접근 방법에서 막힘

**Comment by Blanc-et-noir** [comment]
해당 문제는 맵의 크기가 최대 8x8로 상당히 작고, 세워야 하는 벽의 개수가 3개밖에 되지 않음.
따라서, 백트래킹과 BFS를 조합한다면 쉽게 해결할 수 있을 것으로 보임.

필자가 생각하는 해결 과정은 아래와 같음.

1. 맵의 정보를 입력받음.

   이때, 입력 받은 0의 개수 또한 동시에 카운트 함. 0의 개수를 Z라는 변수로 설정해 둠.
   계산을 용이하게 하기 위함

   맵에 입력된 숫자가 2라면 이는 바이러스 이므로, 해당 바이러스 정보를 큐가 아닌 배열에 저장해 둠.
   큐에 저장해두면 매번 poll( )을 하면서 큐에서 완전히 사라지기 때문에, 다른 배치로 벽을 세웠을 때
   다시 바이러스 정보를 큐에 담아야 하기 때문임.

2. 맵의 크기가 NxM이라면 0부터 N*M-1까지의 정수중에서 3개를 중복, 순서 없이 고르는 조합을 백트래킹을 활용하여 구함.

3. 3개의 정수를 선택했다면, 해당 정수를 각각 M으로 나눈 몫과 나머지를 계산함.

4. 가령 맵의 크기가 세로 6, 가로가 8일때 선택된 정수가 각각 17, 2, 25라면
   1번째 새로 세울 벽은 y좌표가 17/8=2, x좌표가 17%8=1이 됨. (2,1)
   2번째 새로 세울 벽은 y좌표가 2/8=0, x좌표가 2%8=2이 됨. (0,2)
   3번째 새로 세울 벽은 y좌표가 25/8=3, x좌표가 25%8=1이됨. (3,1)
   단, 해당 좌표가 모두 0의 값을 갖는 빈 공간이어야 함.

5. 입력 받았던 바이러스들의 위치가 담긴 배열에서 순차적으로 바이러스를 하나씩 꺼내어 BFS탐색을 수행함.
   바이러스는 상하좌우 4방향으로 이동하되, 기존에 있던 벽 또는 새로 새운 벽을 만날 때 까지만 탐색함.

   각각의 바이러스는 방문배열을 서로 공유하는 것이 시간적으로 효율적임.
   왜냐하면 기존에 다른 바이러스가 이미 지나갔던 공간을 굳이 다시 지나갈 필요가 없기 때문임.

6. 바이러스가 새로 벽이 세워지지 않은 0값을 갖는 공간을 마주했을 때 그 개수를 카운트함. 이를 C라고 하겠음.

7. 벽을 3개 새로 배치하고나서 수행한 BFS탐색이 종료되었을 때, 안전 공간의 개수는 Z - C - 3임.
   왜냐하면 안전 공간은 초기에 Z개였으나, 이중에 3개에 벽을 새로 세웠고, C개는 바이러스에 오염되었기 때문임.

8.  (2,1), (0,2), (3,1) 위치에 벽을 세운 후 수행했던 BFS탐색이 종료되면, 백트래킹을 활용해 다음에 벽을 세울 위치를 고르고
    동일한 과정을 수행하면 됨.

간략하게 말하자면

1. 백트래킹을 활용하여 새로 세울 벽의 위치 3개를 정함.

2. 해당위치에 벽을 세웠다고 가정하고 BFS탐색을 수행함.

3. BFS탐색 종료 시에 Z-C-3을 계산함. 그것이 안전영역의 개수임.

4. 1~3과정을 반복하여 최대 안전영역의 개수를 구함.

**Comment by inseonyun** [comment]
2번에서 만약 N = 8, M = 8이면, N * M -1은 56이 되고 이를 조합하면 (56)Combi(3)이 되는데 시간적으로 문제 없나여?

**Comment by Blanc-et-noir** [comment]
8 * 8 - 1 C 3 = 41664가지의 경우의 수가 존재하나, 그 40000여가지 조합에서 선택된 3개의 좌표가
모두 빈 공간일때만 벽을 세울 수 있으므로 실질적으로는 그보다 적은 경우의 수를 가지게 될 것임.

또한, 맵의 크기가 일반적인 BFS문제와는 달리 최대 8*8로 상당히 작고, 바이러스들 또한 방문배열을 공유하기에
40000여번의 BFS탐색이 금방 종료될 것임.

마지막으로, BFS탐색이 끝났을때, 일일이 이중 for문을 통해 O(N^2)의 시간 복잡도로 안전영역의 크기를 구하지 않고
Z - C - 3이라는 간단한 계산식을 통해 O(1)만에 안전 영역의 크기를 알아낼 수 있으므로 문제될 것이 없음.

**Comment by inseonyun** [comment]
해결했읍니다 감사합니다

![image](https://user-images.githubusercontent.com/84364741/194813173-4369b616-2b50-4f32-97ca-b2bf810d880d.png)

**Comment by inseonyun** [comment]
PR : #167
